import { Question } from "../interfaces/question.interface";

export const QUESTIONS: readonly Question[] = [
  { id: 1, phrase: 'Os meninos foram ao parque brincar.', isCorrect: true },
  { id: 2, phrase: 'Ela trouxe o material para a aula.', isCorrect: true },
  { id: 3, phrase: 'Eu gosto de estudar à noite.', isCorrect: true },
  { id: 4, phrase: 'Vamos ao cinema amanhã?', isCorrect: true },
  { id: 5, phrase: 'Eles já tinham saído quando cheguei.', isCorrect: true },
  { id: 6, phrase: 'A casa foi construída em 1990.', isCorrect: true },
  { id: 7, phrase: 'João e Maria compraram um carro novo.', isCorrect: true },
  { id: 8, phrase: 'O café está quente e cheiroso.', isCorrect: true },
  { id: 9, phrase: 'Ontem choveu bastante na cidade.', isCorrect: true },
  { id: 10, phrase: 'O professor explicou a lição com paciência.', isCorrect: true },
  { id: 11, phrase: 'O cachorro latiu durante a madrugada.', isCorrect: true },
  { id: 12, phrase: 'Preciso de um tempo para pensar.', isCorrect: true },
  { id: 13, phrase: 'As flores estavam lindas no jardim.', isCorrect: true },
  { id: 14, phrase: 'Gostaria de saber a sua opinião.', isCorrect: true },
  { id: 15, phrase: 'Meu irmão trabalha em uma padaria.', isCorrect: true },
  { id: 16, phrase: 'Fizemos tudo conforme as instruções.', isCorrect: true },
  { id: 17, phrase: 'Ele ficou feliz com o resultado.', isCorrect: true },
  { id: 18, phrase: 'A porta estava trancada quando cheguei.', isCorrect: true },
  { id: 19, phrase: 'Minha mãe sempre acorda cedo.', isCorrect: true },
  { id: 20, phrase: 'Este é o livro que eu te falei.', isCorrect: true },
  { id: 21, phrase: 'Eles moram perto da escola.', isCorrect: true },
  { id: 22, phrase: 'Vamos sair assim que a chuva parar.', isCorrect: true },
  { id: 23, phrase: 'A criança dormiu no sofá.', isCorrect: true },
  { id: 24, phrase: 'O filme foi melhor do que eu esperava.', isCorrect: true },
  { id: 25, phrase: 'Ela me emprestou o caderno ontem.', isCorrect: true },
  { id: 26, phrase: 'Os menino foi jogar bola.', isCorrect: false, correctPhrase: 'Os meninos foram jogar bola.' },
  { id: 27, phrase: 'Ela truxe o material pra aula.', isCorrect: false, correctPhrase: 'Ela trouxe o material para a aula.' },
  { id: 28, phrase: 'Eu gosto de estuda de noite.', isCorrect: false, correctPhrase: 'Eu gosto de estudar à noite.' },
  { id: 29, phrase: 'Vamos no cinema amanhã?', isCorrect: false, correctPhrase: 'Vamos ao cinema amanhã?' },
  { id: 30, phrase: 'Eles já tinha saído quando cheguei.', isCorrect: false, correctPhrase: 'Eles já tinham saído quando cheguei.' },
  { id: 31, phrase: 'A casa foi construído em 1990.', isCorrect: false, correctPhrase: 'A casa foi construída em 1990.' },
  { id: 32, phrase: 'João e Maria comprou um carro novo.', isCorrect: false, correctPhrase: 'João e Maria compraram um carro novo.' },
  { id: 33, phrase: 'O café está quente e cheirosa.', isCorrect: false, correctPhrase: 'O café está quente e cheiroso.' },
  { id: 34, phrase: 'Ontem chove bastante na cidade.', isCorrect: false, correctPhrase: 'Ontem choveu bastante na cidade.' },
  { id: 35, phrase: 'O professor explicou a lição com paciença.', isCorrect: false, correctPhrase: 'O professor explicou a lição com paciência.' },
  { id: 36, phrase: 'O cachorro latio durante a madrugada.', isCorrect: false, correctPhrase: 'O cachorro latiu durante a madrugada.' },
  { id: 37, phrase: 'Preciso d’um tempo pra pensa.', isCorrect: false, correctPhrase: 'Preciso de um tempo para pensar.' },
  { id: 38, phrase: 'As flor estava lindas no jardim.', isCorrect: false, correctPhrase: 'As flores estavam lindas no jardim.' },
  { id: 39, phrase: 'Gostaria de saber a sua opnião.', isCorrect: false, correctPhrase: 'Gostaria de saber a sua opinião.' },
  { id: 40, phrase: 'Meu irmão trabalha numa padarinha.', isCorrect: false, correctPhrase: 'Meu irmão trabalha em uma padaria.' },
  { id: 41, phrase: 'Fizemos tudo conforme as instrusão.', isCorrect: false, correctPhrase: 'Fizemos tudo conforme as instruções.' },
  { id: 42, phrase: 'Ele fico feliz com o resultado.', isCorrect: false, correctPhrase: 'Ele ficou feliz com o resultado.' },
  { id: 43, phrase: 'A porta estava trancado quando cheguei.', isCorrect: false, correctPhrase: 'A porta estava trancada quando cheguei.' },
  { id: 44, phrase: 'Minha mãe sempre acorda cedo demais da conta.', isCorrect: false, correctPhrase: 'Minha mãe sempre acorda muito cedo.' },
  { id: 45, phrase: 'Esse é o livro que eu te falei ele.', isCorrect: false, correctPhrase: 'Este é o livro de que eu te falei.' },
  { id: 46, phrase: 'Eles mora perto da escola.', isCorrect: false, correctPhrase: 'Eles moram perto da escola.' },
  { id: 47, phrase: 'Vamos sair assim que a chuva parar-mos.', isCorrect: false, correctPhrase: 'Vamos sair assim que a chuva parar.' },
  { id: 48, phrase: 'A criança dormiu no sofás.', isCorrect: false, correctPhrase: 'A criança dormiu no sofá.' },
  { id: 49, phrase: 'O filme foi melhor do que eu esperava ele.', isCorrect: false, correctPhrase: 'O filme foi melhor do que eu esperava.' },
  { id: 50, phrase: 'Ela me emprestou o caderno ontem pra mim ler.', isCorrect: false, correctPhrase: 'Ela me emprestou o caderno ontem para eu ler.' },
];
